### ISSUE TITLE
Pass custom solutionConfig while creating solution via python sdk

### ISSUE THREAD

**Issue by shim1998** [aws-samples/amazon-personalize-samples#107]
- I am trying to create a solution on AWS Personalise using custom hyperparameter config.
- This is the error I am facing.
```
InvalidInputException                     Traceback (most recent call last)
<ipython-input-63-504a17505a0e> in <module>
      4     datasetGroupArn = dataset_group_arn,
      5     recipeArn = recipe_arn,
----> 6     solutionConfig=solutionConfig
      7 )
      8 
~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    274                     "%s() only accepts keyword arguments." % py_operation_name)
    275             # The "self" in this scope is referring to the BaseClient.
--> 276             return self._make_api_call(operation_name, kwargs)
    277 
    278         _api_call.__name__ = str(py_operation_name)
~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    584             error_code = parsed_response.get("Error", {}).get("Code")
    585             error_class = self.exceptions.from_code(error_code)
--> 586             raise error_class(parsed_response, operation_name)
    587         else:
    588             return parsed_response
InvalidInputException: An error occurred (InvalidInputException) when calling the CreateSolution operation: Provide a hyperparameter that is used in the algorithm: arn:aws:personalize:::algorithm/aws-contextual-bandits
```
This is the solution config that I am passing. 
```
solutionConfig={
  'hpoConfig': {
      'hpoResourceConfig': {
          'maxNumberOfTrainingJobs': '16',
          'maxParallelTrainingJobs': '8'
      },
      'algorithmHyperParameterRanges': {
          'integerHyperParameterRanges': [
              {
                  'name': 'model.num_hidden',
                  'minValue': 32,
                  'maxValue': 256
              },
              {
                  'name': 'training.bptt',
                  'minValue': 2,
                  'maxValue': 32
              }
          ],
          'categoricalHyperParameterRanges': [
              {
                  'name': 'data.recency_mask',
                  'values': ['True', 'False']
              },
          ]     
      }
  },
  'featureTransformationParameters': {
      'max_hist_length_percentile': '0.99',
      'min_hist_length_percentile': '0.00'
  }
}
```
This is how I am invoking the call in python SDK.
```
create_solution_response = personalize.create_solution(
    name = "personalize-soln-user-personalization-test",
    performHPO = True,
    datasetGroupArn = dataset_group_arn,
    recipeArn = recipe_arn,
    solutionConfig=solutionConfig
)
solution_arn = create_solution_response['solutionArn']
```
Any leads on this will be appreciated.

**Comment by ruilinRM** [comment]
Hi, recently I met the same problem, and I fixed it right now.
The cause is:
 _'featureTransformationParameters': {
      'max_hist_length_percentile': '0.99',
      'min_hist_length_percentile': '0.00'
  }_
(maybe you copy this config from other solution that you have created on website)
This should be written as 
_'featureTransformationParameters': {
            'max_user_history_length_percentile': '0.99',
            'min_user_history_length_percentile': '0.00'
        }_

**Comment by shim1998** [comment]
Thank you for your response. However, changing that still doesn't fix this. The error message is same as before. Maybe other params are also wrong. Could you provide me a relevant source?

**Comment by dat181197** [comment]
You should check the docs for the input hyperparameter configs of different recipe, for the User Personalize recipe https://docs.aws.amazon.com/personalize/latest/dg/native-recipe-new-item-USER_PERSONALIZATION.html#bandit-hyperparameters.

Your 'algorithmHyperParameterRanges' should be 
'algorithmHyperParameterRanges': {
          'integerHyperParameterRanges': [
              {
                  'name': **_'hidden_dimension'_**,
                  'minValue': 32,
                  'maxValue': 256
              },
              {
                  'name': **_'bptt'_**,
                  'minValue': 2,
                  'maxValue': 32
              }
          ],
          'categoricalHyperParameterRanges': [
              {
                  'name': _**'recency_mask'**_,
                  'values': ['True', 'False']
              },
          ]     
      }

**Comment by davidguzmanr** [comment]
I had a similar issue, it seems that `'continuousHyperParameterRanges'` can't be null, adding `'continuousHyperParameterRanges': []` did the job for me, so your configuration would look like this

```python
'hpoConfig': {        
        'hpoResourceConfig': {
            'maxNumberOfTrainingJobs': '16',
            'maxParallelTrainingJobs': '8'
        },
        'algorithmHyperParameterRanges': {
            'integerHyperParameterRanges': [
                {
                    'name': 'hidden_dimension',
                    'minValue': 32,
                    'maxValue': 256
                },
                {
                    'name': 'bptt',
                    'minValue': 2,
                    'maxValue': 32
                },
            ],
            'categoricalHyperParameterRanges': [
                {
                    'name': 'recency_mask',
                    'values': ['true', 'false']
                }
            ],
            'continuousHyperParameterRanges': [] 
        }
        
    }
```
